### ISSUE TITLE
White Screen on Segment Plugin when using REGEXP of large list

### ISSUE THREAD

**Issue by TBart777** [bramley/phplist-plugin-segment#3]
Hi there, I hope that I'm submitting this bug notification in the right place. I have a large list of almost 500 000, and I have a Date of Birth attribute with the format CCYYMMDD. I've been using a REGEXP ^([1][9][0-8][0-9]|[1][9][9][0]) to segment subscribers over 25, and the issue only appeared when the list grew to over 400 000, but now I get a white screen and the campaign becomes corrupt and irrepairable. Would you be so kind as to point me to where I may adjust your code to compensate? Many thanks, Tony.

**Comment by bramley** [comment]
You will need to use phpmyadmin or a similar sql tool to delete a row from the messagedata table.
Delete the row with id = the message id, and name = 'segment'. That will remove the conditions for that particular message, which should allow you to continue.
The plugin builds an array of the selected subscribers, which might not be a good idea when you have 400,000. I will take a look at the code to see whether that can be improved.

**Comment by TBart777** [comment]
Hi Duncan,

 

I really appreciate your taking the time to respond to my issue, and thank you for the recovery solution. 

 

REGEXP though isn’t very well suited to numeric field values, would it be worthwhile to add ‘more than’ and ‘less than’ operators ?

 

Thanks again for a much needed addition to phpList.

 

Best Regards,

 

 

Tony Bartok

Business Development Director



Email:  <mailto:tony@mailmarket.co.za> tony@mailmarket.co.za

Web:  <http://www.axiontec.com/> www.mailmarket.co.za
Tel: 0861 256442

**Comment by bramley** [comment]
It should be possible to add 'greater' and 'less' operators but that would probably need to handle numeric values as a special case, because the attribute value is a string as is the target value. A simple comparison of two strings will lead to unexpected results, such as 11 < 2 when compared as strings.

But in your case changing the attribute to be a date attribute instead of a text line attribute would make things easier. The plugin already has before, after and between operators for a date.

**Comment by TBart777** [comment]
Hi Duncan,

 

You mentioned that you managed to figure out why the segment plugin crashes when segmenting large databases, is this something that you might consider as a bug to fix?

 

On another note, our database has 3 attributes with numeric values, but as you rightly pointed out, the ‘Date of Birth’ attribute would be much more intuitive to segment as a format, rather than as numeric… that said, I’m gonna have to figure out how to convert a textline field with format CCYYMMDD into a date. 

 

Thanks again for your time, input and suggestions, you’ve been most helpful. Have a great weekend.

 

Best Regards,

Tony

**Comment by bramley** [comment]
I am guessing that the cause of your problem is excessive memory usage when calculating the number of subscribers. I have made some changes to the plugin to be more efficient in memory usage when doing that calculation, so please can you upgrade the plugin to the latest version (on the Manage Plugins page).

Also, please can you either use GitHub directory to add a comment, or if you use the email reply, please trim the email to be just your comment and not the email trail. That helps to keep the issue trail reasonably clear.

**Comment by TBart777** [comment]
Hi Duncan, Many thanks for fixing this issue! It works great now.
